### ISSUE TITLE
How to use with apollo-server-express?

### ISSUE THREAD

**Issue by mrceperka** [koresar/graphql-upload-minimal#1]
Hello,
`apollo-server-express` got `graphql-upload` built in. How do I force it to use this package?

Some `resolve` hacks?

I am trying to make it work with `nestjs` but no success so far.

```ts
// main.ts
import { ValidationPipe } from "@nestjs/common";
import { NestFactory } from "@nestjs/core";
import {
  ExpressAdapter,
  NestExpressApplication,
} from "@nestjs/platform-express";
import express from "express";
import { graphqlUploadExpress } from "graphql-upload-minimal";

import { AppModule } from "./app.module";

const expressApp = express().use(
  "/graphql",
  graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 })
);
async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(
    AppModule,
    new ExpressAdapter(expressApp)
  );

  // Validation
  app.useGlobalPipes(new ValidationPipe());

  // Cors
  if (process.env.CORS_ENABLE === "1") {
    app.enableCors();
  }
  return app;
}

async function main() {
  const app = await bootstrap();
  await app.listen(process.env.PORT || 5000);
}

main();
```

```ts
// main app.module
import { FirebaseAdminModule } from "@aginix/nestjs-firebase-admin";
import { Module } from "@nestjs/common";
import { ConfigModule, ConfigService } from "@nestjs/config";
import { GraphQLModule } from "@nestjs/graphql";
import * as admin from "firebase-admin";

@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    GraphQLModule.forRootAsync({
      useFactory: async (configService: ConfigService) => ({
        autoSchemaFile:
          configService.get("GRAPHQL_SCHEMA_DEST") || "./src/schema.graphql",
        debug: configService.get("GRAPHQL_DEBUG") === "1" ? true : false,
        playground:
          configService.get("GRAPHQL_PLAYGROUND_ENABLE") === "1" ? true : false,
        context: ({ req, res }) => ({ req, res }),
      }),
      inject: [ConfigService],
    }),
    FirebaseAdminModule.forRootAsync({
      useFactory: (configService) => ({
        credential: admin.credential.applicationDefault(),
        databaseURL: configService.get("FIREBASE_DATABASE_URL"),
        storageBucket: configService.get("FIREBASE_STORAGE_BUCKET"),
      }),
      inject: [ConfigService],
    }),
  ],
  providers: [AppService, AppResolver],
})
export class AppModule {}
```

GraphQL itself works, but uploads does not. I am getting this error:
```
 +4158ms
[Nest] 4692   - 06/06/2020, 10:18:51 AM   [ExceptionsHandler] Object:
[
  {
    "message": "Request disconnected during file upload stream parsing.",
    "extensions": {
      "code": "INTERNAL_SERVER_ERROR",
      "exception": {
        "stacktrace": [
          "BadRequestError: Request disconnected during file upload stream parsing.",
          "    at IncomingMessage.abort (/var/bb/node_modules/graphql-upload/lib/processRequest.js:89:33)",
          "    at Object.onceWrapper (events.js:421:28)",
          "    at IncomingMessage.emit (events.js:327:22)",
          "    at abortIncoming (_http_server.js:533:9)",
          "    at socketOnClose (_http_server.js:525:3)",
          "    at Socket.emit (events.js:327:22)",
          "    at TCP.<anonymous> (net.js:674:12)"
        ]
      }
    }
  }
]
 +510ms
```

Which looks like it is still using `graphql-upload` package and not this one :/

**Comment by koresar** [comment]
Oh. I feel silly. Sorry, looks like I mislead you and other people who are using `apollo-graphql-XXX` modules.
The `apollo-graphql-` modules have the `graphql-upload` built-in and does not allow replacing it of course.

Looks like when both "graphql-upload-..." modules are used in a project one of them gets crazy and throws.

**Comment by koresar** [comment]
Looks like you're trying to add file uploads to a serverless function. AFAIK, `graphql-upload` does not work in serverless functions at all. I can be wrong here though.

**Comment by mrceperka** [comment]
It's not serverless, standard node app. Running in docker container on my machine.

Probably, if this package have had **exactly** same API as `graphql-upload`, it could have been used instead of `graphql-upload` with apollo-server.

**Comment by koresar** [comment]
It has exactly same API. I looked up what apollo-server-core is using.

Here is how you can replace "graphql-upload" with "graphql-upload-minimal":

`npm i override-require`

And on the node.js process start:

```js
require("override-require")(m => m === "graphql-upload", require("graphql-upload-minimal"));


```

**Comment by mrceperka** [comment]
Sounds promising. Thanks for a tip. Will try later.

**Comment by koresar** [comment]
Waiting for more comments. Meanwhile, closing this issue.
